# This is a basic workflow to help you get started with Actions

name: work-ci-test 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ ci-test-workflow]
  pull_request:
    branches: [ ci-test-workflow]
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      ## install rust
      #- name: Install Rust use Substrate actions script
      #  uses: digitalnativeinc/install-rust-substrate-action@0.4.0

      ## debug 
      #- name: debug 
      #  run: |
      #     cargo --version 

      ## install go
      #- name: Set up Go 1.16
      #  uses: actions/setup-go@v2.1.4
      #  with:
      #    go-version: "1.16.x"

      ## install db
      #- uses: harmon758/postgresql-action@v1
      #  with:
      #    postgresql version: '12' 

      ## configure db
      ## to do
      #      
      ## install oasis-node
      #- name: install oasis node
      #  run: |
      #     ls
      #     cd ../../
      #     wget https://github.com/oasisprotocol/oasis-core/releases/download/v21.3.5/oasis_core_21.3.5_linux_amd64.tar.gz 
      #     ls
      #     pwd
      #     mkdir -p oasis-node/bin
      #     cd ./oasis-node/bin
      #     pwd 
      #     tar xf ../../oasis_core_21.3.5_linux_amd64.tar.gz --strip-components=1  

      # checks-out evm-paratime
      - name: Checkout evm paratime
        uses: actions/checkout@v2
        with:
            repository: starfishlabs/oasis-evm-paratime
            ref: main 
            path: ./oasis-evm-paratime

      # debug 
      - name: debug 
        run: |
           pwd
           ls


      # checkout-out web3gateway
      - name: checkout web3gateway 
        uses: actions/checkout@v2
        with: 
            ref: main
            path: ./oasis-evm-web3-gateway

      # start evm-paratime
      - name: start evm paratime
        run:  |
            pwd
            ls
            cd ..
            pwd
            ls
      #      cargo build
      #      cd oasis/oasis-evm-paratime
      #      #################################
      #      timeout 10m bash start.sh &  

      ## start web3gateway
      #- name: start web3gateway 
      #  run:  |
      #      cd ./oasis/oasis-evm-web3-gateway
      #      go build
      #      timeout 10m bash ./oasis-evm-web3-gateway &

      ## run test
      #- name: run test 
      #  run:  |
      #      cd ./oasis/oasis-evm-web3-gateway/tests/rpc
      #      go test